version: "3.1"

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    volumes:
      - data-psql:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  backend:
    image: backend_django:1.0.0
    ports:
      - "8000:8000"
    command: bash -c "gunicorn TODO.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
  nginx:
    image: drf_nginx:1.0.0
    ports:
      - "8080:80"
    depends_on:
      - backend
  frontend:
    image: frontend_react:1.0.0
    ports:
      - "80:80"
    depends_on:
      - nginx

volumes:
  data-psql:
